services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount source code for development (comment out for production)
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  # Development service (alternative to production build)
  nextjs-dev:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    profiles:
      - dev